import {  SignInButton, SignOutButton, SignUpButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  const user= useUser();
  
 

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user.isSignedIn ?
      <SignOutButton>Sign Out</SignOutButton>:
    
      <SignInButton>siGN IN2222</SignInButton>}
    </>
  );
};

export default Home;
